# dotfiles-Alpine/Makefile — the local mirror of CI, and nothing more.
#
# This adds NO logic of its own: every target runs the same tool, with the same flags
# and the same excludes, that dotfiles-core's reusable gate runs in CI
# (core/.github/workflows/lint-call.yml). Same convention as core/Makefile — the
# scripts and workflows stay the single source of truth; this is just the button.
#
# WHY IT EXISTS: until now every check in this repo was CI-only, so the first signal
# that a change was broken arrived after the push — and with CI advisory rather than
# required, sometimes not at all.
#
# A missing tool SKIPs with a note instead of failing, so a box without actionlint can
# still run the shell gate. CI is the strict mirror; this is the fast one.

SHELL := /bin/sh
.DEFAULT_GOAL := help

# Repo-owned files only. core/ is a vendored subtree gated by its own upstream CI;
# linting it here would report findings this repo is not allowed to fix.
SH_FILES  := $(shell git ls-files '*.sh' ':!:core/**')
ZSH_FILES := $(shell git ls-files '*.zsh' ':!:core/**')

# Identical to the reusable gate's env, so a local pass means a CI pass.
export SHELLCHECK_OPTS := -e SC1090 -e SC1091 -e SC2015 -e SC2088

.PHONY: help check shell zsh actions md secrets verify-core dry-run hooks

help:
	@echo 'dotfiles-Alpine — local gates (mirror of CI)'
	@echo ''
	@echo '  make check        every gate below, in order'
	@echo '  make shell        shellcheck + bash -n on repo-owned *.sh'
	@echo '  make zsh          zsh -n on repo-owned *.zsh (incl. zsh/zshenv.zsh)'
	@echo '  make actions      actionlint on .github/workflows'
	@echo '  make md           markdownlint-cli2 on tracked markdown'
	@echo '  make secrets      gitleaks over the working tree'
	@echo '  make verify-core  is the vendored core/ still pristine vs core.lock?'
	@echo '  make dry-run      preview the bootstrap wiring; change nothing'
	@echo '  make hooks        install the pre-commit hooks'

check: shell zsh actions md secrets
	@echo '✓ all local gates passed'

shell:
	@command -v shellcheck >/dev/null 2>&1 || { echo '- shellcheck not installed — SKIP'; exit 0; }; \
	  [ -n "$(SH_FILES)" ] || { echo '- no repo-owned *.sh'; exit 0; }; \
	  echo ':: shellcheck $(SH_FILES)'; shellcheck $(SH_FILES)
	@[ -n "$(SH_FILES)" ] || exit 0; \
	  for f in $(SH_FILES); do echo ":: bash -n $$f"; bash -n "$$f" || exit 1; done

zsh:
	@command -v zsh >/dev/null 2>&1 || { echo '- zsh not installed — SKIP'; exit 0; }; \
	  [ -n "$(ZSH_FILES)" ] || { echo '- no repo-owned *.zsh'; exit 0; }; \
	  for f in $(ZSH_FILES); do echo ":: zsh -n $$f"; zsh -n "$$f" || exit 1; done

actions:
	@command -v actionlint >/dev/null 2>&1 || { echo '- actionlint not installed — SKIP'; exit 0; }; \
	  echo ':: actionlint'; actionlint -color

# Markdown is the deliverable on a public showcase repo and the one file class that
# shellcheck / zsh -n never inspect. .markdownlint.jsonc has always been here; until
# now nothing ran it (the lint workflow skipped **.md outright), so it was decoration.
md:
	@command -v markdownlint-cli2 >/dev/null 2>&1 || { echo '- markdownlint-cli2 not installed — SKIP'; exit 0; }; \
	  echo ':: markdownlint-cli2'; markdownlint-cli2 $$(git ls-files '*.md' ':!:core/**')

# This repo tracks ssh/config and is public. Core runs gitleaks at author time and in
# its audit; nothing ran it here. GitHub push protection covers provider patterns only.
secrets:
	@command -v gitleaks >/dev/null 2>&1 || { echo '- gitleaks not installed — SKIP'; exit 0; }; \
	  echo ':: gitleaks'; gitleaks dir . --no-banner --redact

# Content-addressed tamper check: does HEAD:core still match the commit core.lock
# pins? Delegates to Core's own script — this repo does not reimplement it.
#
# It must be run from a dotfiles-core CHECKOUT, not from the vendored copy under
# core/: the check resolves <core_sha>^{tree} in Core's object store, and this repo's
# history does not contain Core's commits (git subtree --squash brings the tree, not
# the lineage). That is also exactly how CI invokes it — core-integrity-call.yml runs
# ./dotfiles-core/scripts/core-integrity.sh --self <os-repo>. Override the location
# with:  make verify-core CORE_REPO=/path/to/dotfiles-core
#
# NB: there is deliberately no `core-lock` target, despite core.lock's own header
# instructing `make core-lock`. That file is GENERATED by dotfiles-core's
# sync-core.sh; a second generator living here could drift from upstream's format and
# produce a lock that disagrees with the fleet. The header is an upstream doc bug.
CORE_REPO ?= ../dotfiles-core

verify-core:
	@[ -x "$(CORE_REPO)/scripts/core-integrity.sh" ] || { \
	    echo '- no dotfiles-core checkout at $(CORE_REPO) — SKIP'; \
	    echo '  (clone it beside this repo, or: make verify-core CORE_REPO=/path/to/dotfiles-core)'; \
	    exit 0; }; \
	  "$(CORE_REPO)/scripts/core-integrity.sh" --self "$(CURDIR)"

dry-run:
	@./bootstrap.sh --dry-run

hooks:
	@command -v pre-commit >/dev/null 2>&1 || { echo 'pre-commit not installed: pip install pre-commit'; exit 1; }; \
	  pre-commit install
